
# this if the folder path to the static images that have to be
# displayed in the frontend
# this folder contains 13 additional folder each for one language
#commented below line by Vineet
#STATIC_IMAGE_FOLDER = '/home/krishna/pageocr/frontend/static/images'
#added below line by Vineet
STATIC_IMAGE_FOLDER = './static/images'

# this is the path to the layout files for each of the image
# the name of the json files mirror the names of the image files
# for which the output is stored
#commented below line by Vineet
#STATIC_LAYOUT_FOLDER = '/home/krishna/pageocr/frontend/static/layouts'
#added below line by Vineet
STATIC_LAYOUT_FOLDER = './static/layouts'

MT_ACCESS_TOKEN = """eyJ4NXQiOiJZV1kxTm1Sa1pHSTVNekU0T0RCbFpEUmlNV0k0WldKbE5qRXhaV1ZpWmpFek1tTm1ORFUzWVEiLCJraWQiOiJNV1E1TldVd1lXWmlNbU16WlRJek16ZG1NekJoTVdNNFlqUXlNalZoTldNNE5qaGtNR1JtTnpGbE1HSTNaRGxtWW1Rek5tRXlNemhoWWpCaU5tWmhZd19SUzI1NiIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiI3YmEyNzY3YS0wM2ZiLTRlNzQtOWQzMi01Y2NkM2QxZDgyZjciLCJhdXQiOiJBUFBMSUNBVElPTiIsImF1ZCI6IkFBZG9KZmRKTjRMS1llZEpYMklLNGFSanA1NGEiLCJuYmYiOjE2Njk4OTA0NTAsImF6cCI6IkFBZG9KZmRKTjRMS1llZEpYMklLNGFSanA1NGEiLCJzY29wZSI6ImRlZmF1bHQiLCJvcmdhbml6YXRpb24iOnsidXVpZCI6IjExZmMwNDY4LTY0NGMtNGNjNi1iZTdkLTQ2YjViZmZjZDkxNCJ9LCJpc3MiOiJodHRwczpcL1wvc3RzLmNob3Jlby5kZXY6NDQzXC9vYXV0aDJcL3Rva2VuIiwiZXhwIjoxNjY5ODk0MDUwLCJpYXQiOjE2Njk4OTA0NTAsImp0aSI6ImM3YzdlNjdiLWMwZDYtNGQ0MC1hMWJmLTM5ODhkNmRhMTM0NSJ9.QzOuZBp9qiMX1oQKqYMYCTKJ8TTH2wcOiVmDt1kFx37ZOdmwXJhljJS6q-lH2W1NSrk_nF2atc0p0NbT-aPARYJC2OXDSsyRwGwo-kkdjb0D9PT-rsR4p5KFZqCEnbo0jU1ghUpw1oI7sperVIgBLOeW-fcD4xotlyAZEvCoTlZcgsj8mPW9KMEPjcQ4r6pQucCbOoa8mv1kLw7J3v4q_BqFO2qjyKug-DWYQMNWphXjvPSIU-sUR6asPWwHoKSioWhGwwE7FzJLsyH-s0tHreKa8IkKmhpf2wl8NWc9qnB9hMr2uAiKZyjmHjyAvjFfpXAmrC2EhrRM4-2ydvG0JJDDPW6URwAGFAhkWfPo26mPfU8VBz7uKz3iBlWu0lDCQqNHsB0ftXXr6oezaNdgEB9MyVO41OWLDd9ArykGXoKeQp_-iI4ZfS2UDNc6ZIF3EtB-tkUTTgCIfESX-ChYaeihGqlEzn1rDTSgT7k-jIYx3w6OgQhTf_uxErAFm8w-moztPC9YCSYTYWT3DxE1eLccDL_2AM-_nf9zdYBXNUuZvZl70vK17PSGR6jwu37LgouRaexPA9zPEtHDRwA-KpeHJpMLpy-zY4N5QGWvHdbSo72bJGF-Vwq5KkItuJqbplRMiaSPQVYYxfSq8kZDKWDRN-fgbXVE5DYxHTsLP1U"""